export const siteContent = {
  person: "Carlota Ortiz",
  currentYear: new Date().getFullYear(),
  nav: [
    { label: "About", href: "#about" },
    { label: "Expertise", href: "#expertise" },
    { label: "Experience", href: "#experience" },
    { label: "Projects", href: "#projects" },
    { label: "Education", href: "#education" },
    { label: "Contact", href: "#contact" },
  ],
  hero: {
    heading: "Building the teams behind breakthrough technology.",
    intro: [
      "I’m Carlota Ortiz, a Senior HR Business Partner focused on helping technology and research organisations grow through people strategy, organisational design, and strategic hiring.",
      "Over the last decade, I have worked with international companies at different stages of growth, partnering with leaders to build strong teams and scalable organisations.",
    ],
  },
  story: [
    "I did not begin my career with a fixed plan to work in HR.",
    "What has always interested me is understanding how organisations work, why some teams achieve exceptional results, and what allows people to perform at their best.",
    "My career began in Talent Acquisition, where I learned that hiring is not simply about filling vacancies. It is about understanding what a business needs, identifying people who can make a meaningful contribution, and creating the conditions for them to succeed.",
    "I joined Nordcloud during a period of rapid growth, working closely with technical and business leaders as the company expanded internationally.",
    "Over time, I became increasingly interested in the broader questions behind hiring: how teams should be structured, which capabilities a business needs, how organisations can scale sustainably, and how people strategy can support long-term goals.",
    "That progression led me into HR Business Partnering.",
    "Today, I work at Huawei R&D Switzerland, partnering with leaders in a highly international research and technology environment.",
    "What I enjoy most is helping organisations build the teams, structures, and people practices they need to grow and solve meaningful problems.",
  ],
  whatIDo: {
    intro: "I see HR as a strategic function that helps organisations make better decisions about people, structure, and growth.",
    questions: [
      "How should a team evolve as the organisation grows?",
      "Which capabilities are currently missing?",
      "What type of talent would create the greatest impact?",
      "How can hiring decisions become more structured and evidence-based?",
      "How can an organisation scale without losing quality?",
      "How should roles and responsibilities evolve over time?",
    ],
  },
  expertise: [
    ["Strategic HR Partnership", "Connecting people strategy with organisational and business priorities."],
    ["Strategic Hiring", "Helping organisations identify and attract the talent needed for future growth."],
    ["Organisational Design", "Supporting leaders in defining effective team structures, roles, and capabilities."],
    ["Structured Interviewing", "Designing fair and evidence-based interview and assessment processes."],
    ["Compensation and Market Intelligence", "Using market information to support competitive and equitable people decisions."],
    ["Performance and Organisational Change", "Advising leaders through performance matters, change, and evolving organisational needs."],
    ["HR Process Improvement", "Building practical and scalable people processes across the employee lifecycle."],
  ],
  experience: [
    {
      company: "Huawei R&D Switzerland",
      role: "Senior HR Business Partner",
      location: "Lausanne, Switzerland",
      period: "2025 – Present",
      description: "Partnering with research and technology leaders on people strategy, organisational growth, and specialised talent.",
    },
    {
      company: "Nordcloud, an IBM Company",
      role: "Senior Global Talent Partner",
      location: "London, United Kingdom",
      period: "2021 – 2025",
      description: "Joined during a period of rapid international growth and progressed from technical recruitment into a senior global talent role.",
    },
  ],
  projects: [
    {
      name: "FAInd",
      subtitle: "AI Talent Intelligence Platform",
      description: "An AI-powered talent sourcing project designed to make the discovery of specialised research and engineering talent more effective.",
      href: "https://github.com/Carlota0612",
      cta: "GitHub profile",
    },
    {
      name: "Personal Website",
      description: "A personal website built with Next.js, TypeScript, GitHub, and Render.",
      href: "https://github.com/Carlota0612",
      cta: "View GitHub",
    },
  ],
  education: [
    ["MBA", "EAE Business School", "2018"],
    ["Master’s Degree in Human Resources", "EAE Business School", "2017"],
    ["Bachelor’s Degree in Tourism and Business", "University of Seville", "2011"],
  ],
  beyondWork: ["Endurance sports", "Swiss Alps hiking", "Painting", "Recruiting technology"],
  approach: "Great companies are not built by hiring the most people.\n\nThey are built by hiring the right people, creating the right environment, and helping talented individuals do the best work of their careers.",
  contact: {
    intro: "I’m always happy to connect with people interested in technology, research, organisational growth, and the future of work.",
    email: "carlota.mortiz@gmail.com",
    linkedin: "https://linkedin.com/in/carlota-o-336058a8",
    github: "https://github.com/Carlota0612",
    location: "Lausanne, Switzerland",
  },
} as const;
